title: Dario Bellicoso
logo: images/alma_pic.png
email: dbellicoso@bostondynamics.com
description: Robotics Research Scientist
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
url: "https://dbellicoso.github.io/"
# twitter_username: leggedrobotics
github_username:  dbellicoso
github:
  is_project_page: true
  owner_url: dbellicoso.github.io
  owner_name: dbellicoso
